# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: someng <someng@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/21 14:44:47 by kaan              #+#    #+#              #
#    Updated: 2023/11/28 17:53:42 by someng           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

make:
	cc ft_printf.c ft_putchar.c ft_strlen.c ft_putstr.c ft_putnbr.c spec_handle_1.c spec_handle_2.c ft_puthex.c && ./a.out
